In [21]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('/Users/wangjinling/Documents/Github/Element of statistical learning/vowel.csv')

In [17]:
data2 = data.values[:, 1:]

In [11]:
y = data2[:, 0]
x = data2[:, 1:]

In [22]:
mu=[]
for j in range(11):
    VX = np.mean(x[y==j+1,:], axis = 0)
    mu.append(VX)

###analysis of ST data

In [24]:
path = "/Users/wangjinling/Documents/Github/Element of statistical learning/iris.csv"
data = pd.read_csv(path)

In [93]:
y = data.Species == 'setosa'
x = data.values[:, :4]
x = x.astype(np.float_)

In [94]:
import numpy.linalg as la
beta_ols = la.inv(x.T.dot(x)).dot(x.T).dot(y)

In [95]:
beta_ols

array([ 0.08340756,  0.25331855, -0.2270494 , -0.06351371])

In [100]:
beta = beta_ols
for j in range(8):
    tmp = np.exp(x.dot(beta))
    p = tmp / (1 + tmp)
    W = np.diag(p*(1-p))
    z = x.dot(beta) + la.inv(W).dot(y-p)
    beta = la.inv(x.T.dot(W).dot(x)).dot(x.T).dot(W).dot(z)

In [87]:
beta = beta_ols

In [88]:
tmp = np.exp(x.dot(beta))

In [89]:
p = tmp / (1 + tmp)

In [99]:
beta

array([-0.01633122,  4.32142149, -3.70239221, -3.13961771])

In [118]:
from sklearn import linear_model
logreg = linear_model.LogisticRegression(C = 1)
logreg.fit(x, np.asarray(y))

LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, penalty='l2', random_state=None, tol=0.0001)

In [119]:
logreg.coef_

array([[ 0.41021713,  1.46416217, -2.26003266, -1.02103509]])

In [111]:
linear_model.LogisticRegression?